config handling and Sam auth [risk: low]
broadinstitute/lomax pull request #6
Opened 2019-02-28 21:02 UTC by davidangb

don't review yet - making sure mockserver implementation works with Circle tests.

2019-03-01 19:59 UTC, gpolumbo-broad requested changes
Sorry if it's a dumb question, but if this is going to be deployed as cloud functions, just make sure you're throwing and logging errors according to Google's guidelines.  Otherwise 👍

2019-03-01 19:59 UTC, gpolumbo-broad commented on function/dataaccess/sam.js
> +const checkUserEnabled = async (appConfig, authToken) => {
Big method.  Consider refactoring into smaller methods.

Ah, yeah, I see your TODO further down now.

2019-03-01 19:59 UTC, gpolumbo-broad commented on function/dataaccess/sam.js
> +          throw err;
https://cloud.google.com/functions/docs/monitoring/error-reporting 

Make sure you're throwing/recording errors per their guidelines

Is this going to run as Google Cloud Functions?  Or will it be deployed elsewhere?

2019-03-04 20:18 UTC, davidangb commented
thanks  @gpolumbo-broad !  Yes, this will be a cloud function (doc at https://docs.google.com/document/d/1DXvkL8NcmIDMAwN1_tB0RgQO6XJr0jf6xKiRXf2I3nQ).

I've updated the Express error handler to log errors. Everything should bubble up to there so it's a good central place to handle logging.

2019-03-05 22:15 UTC, gpolumbo-broad approved these changes

2019-03-06 11:32 UTC, merged